### ISSUE TITLE
Source code is missing

### ISSUE THREAD

**Issue by stinos** [BlackrockNeurotech/Python-Utilities#2]
Any chance the source is going to end up here?

I have a bunch of changes which might be helpful for others: making reading of continuous data configurable and allowing to fetch data by label not id. That last one is actually pretty important: as far as I can tell the electrode label is what remains constant across different systems, whereas the ID does not, so looking up by ID is a source of mistakes. So for instance on a 128ch system requesting  ID 67 gives data of electrode number 67. On a system with only 64 channels however, it will give data of analog channel 3. That doesn't happen when data can be referred to by `elec67` and `ainp3`.

**Comment by cboulay** [comment]
Hi @stinos ,
Is this for online access to the NSP?
Would you by any chance be interested in contributing to [CereLink](https://github.com/dashesy/CereLink/) and its Python wrapper?
If there is an "official" python interface to the NSP then I would sure love to know about it because I'd rather pool efforts than waste my effort on something no one will ever use :/

**Comment by cboulay** [comment]
And for loading nsx files, I highly recommend [python-neo](https://github.com/NeuralEnsemble/python-neo). There are a few people there who diligently maintain the nsx importer.

**Comment by stinos** [comment]
> Is this for online access to the NSP?

@cboulay the code I was talking about here is the 'official' nsx loader `brPy` which can currently be downloaded from https://www.blackrockmicro.com/wp-content/software

> Would you by any chance be interested in contributing to CereLink and its Python wrapper?

I'm already using CereLink as-is actually. I do have some notes about things which could be improved (IIRC performance-wise mostly, like allowing to set a filter on the events returned by trial_events instead of always returning everything) but the data acquisition is just a tiny part of all projects I'm working on, so unfortunately no time to contribute at the moment.

> I highly recommend python-neo.

Thanks, I didn't even know that. A pity, because we also use other data acquisition systems and the idea of accessing them all through the same interface is of course awesome. Now we already have code working with brPy so there's not a lot of drive to switch to something else though the disadvantages of brPy (rather slow, IIRC because it does a ton of seek() calls which wrecks loading speed over a network, and not in git/community-driven) might make it worthwile anyway. However from a rather brief look at the neo code for loading nsx files it seems to suffer the same problem mentioned above; e.g. it starts with stating "The neural data channels are 1 - 128. The analog inputs are 129 - 144." but that is inaccurate as laid out above, plus the code looks like it also retrieves data by id and not by label so I'd have the same problem with it. Also not ideal that here are 2 different loaders which at first sight seem to do the same.

**Comment by cboulay** [comment]
Give that this post is almost 3 years old and that the brPy source is now included in the repository, I think the main issue is now solved so I will close this issue.

Any users coming to this issue for the secondary issue around indexing channels by id / label are invited to open a new issue.
